/**
 * gen-env.js — Build step that emits a client-safe `env.js`.
 * Reads ONLY public values from the environment and writes globalThis.__ENV__.
 * Run automatically by `npm run build` (Vercel buildCommand). NEVER expose
 * service-role keys or client secrets here — only the anon/public config.
 */
import { writeFileSync, readFileSync, existsSync } from 'node:fs';

const envVars = {};

// Load .env.local if exists
try {
  const filePath = new URL('../.env.local', import.meta.url);
  if (existsSync(filePath)) {
    const content = readFileSync(filePath, 'utf8');
    content.split(/\r?\n/).forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;
      const idx = trimmed.indexOf('=');
      if (idx > 0) {
        const key = trimmed.substring(0, idx).trim();
        let val = trimmed.substring(idx + 1).trim();
        if (val.startsWith('"') && val.endsWith('"')) val = val.slice(1, -1);
        if (val.startsWith("'") && val.endsWith("'")) val = val.slice(1, -1);
        envVars[key] = val;
      }
    });
  }
} catch (e) {
  console.warn('[gen-env] could not parse .env.local file:', e.message);
}

const PUBLIC_KEYS = ['VITE_SUPABASE_URL', 'VITE_SUPABASE_ANON_KEY', 'APP_BASE_URL', 'MS_GRAPH_SCOPES', 'AZURE_AD_CLIENT_ID', 'AZURE_AD_TENANT_ID', 'POWERBI_WORKSPACE_ID'];

const env = Object.fromEntries(PUBLIC_KEYS.map((k) => [k, process.env[k] ?? envVars[k] ?? '']));
const out = `/* generated by scripts/gen-env.js — do not edit, do not commit */\nglobalThis.__ENV__ = ${JSON.stringify(env, null, 2)};\n`;
writeFileSync(new URL('../env.js', import.meta.url), out);
console.log('[gen-env] wrote env.js with keys:', PUBLIC_KEYS.join(', '));
