-- =============================================================================
-- 0006_ecm_core.sql
-- Module 1: Core change records — ECM master, ECR, ECO, links, affected items,
-- and the append-only state transition history.
-- =============================================================================

-- ---- ECM master request -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ecm_requests (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ecm_number                citext UNIQUE,                       -- generated by trigger (0009)
  title                     text NOT NULL,
  description               text,
  reason                    text,
  change_type               text NOT NULL DEFAULT 'standard'
                              CHECK (change_type IN ('standard','emergency','deviation','pre_series','cost_down')),
  affected_part_number      text,
  affected_bom              text,
  primary_item_id           uuid REFERENCES items(id)     ON DELETE SET NULL,
  customer_id               uuid REFERENCES customers(id) ON DELETE SET NULL,
  supplier_id               uuid REFERENCES suppliers(id) ON DELETE SET NULL,
  department_id             uuid REFERENCES departments(id) ON DELETE SET NULL,
  plant_id                  uuid REFERENCES plants(id)    ON DELETE SET NULL,
  priority                  priority_level NOT NULL DEFAULT 'medium',
  risk_level                risk_level     NOT NULL DEFAULT 'low',
  cost_impact               numeric(14,2),
  cost_currency             text NOT NULL DEFAULT 'EUR',
  owner_id                  uuid REFERENCES profiles(id)  ON DELETE SET NULL,
  requestor_id              uuid NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
  -- workflow position (all FKs into the data-driven engine)
  workflow_id               uuid REFERENCES wf_workflows(id) ON DELETE SET NULL,
  current_stage_id          uuid REFERENCES wf_stages(id)    ON DELETE SET NULL,
  current_state_id          uuid REFERENCES wf_states(id)    ON DELETE SET NULL,
  status_category           citext REFERENCES wf_state_categories(code),  -- denormalized cache (trigger-maintained)
  state_entered_at          timestamptz NOT NULL DEFAULT now(),
  source                    change_source NOT NULL DEFAULT 'manual',
  d365_reference            text,
  created_date              date NOT NULL DEFAULT CURRENT_DATE,
  due_date                  date,
  target_implementation_date date,
  closed_at                 timestamptz,
  search_tsv                tsvector,                           -- maintained in 0008
  is_deleted                boolean NOT NULL DEFAULT false,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  created_by                uuid REFERENCES profiles(id) ON DELETE SET NULL,
  updated_by                uuid REFERENCES profiles(id) ON DELETE SET NULL
);
COMMENT ON TABLE ecm_requests IS 'Master engineering change record. Progresses through the data-driven workflow.';
CREATE INDEX IF NOT EXISTS idx_ecm_state       ON ecm_requests (current_state_id);
CREATE INDEX IF NOT EXISTS idx_ecm_stage       ON ecm_requests (current_stage_id);
CREATE INDEX IF NOT EXISTS idx_ecm_status_cat  ON ecm_requests (status_category);
CREATE INDEX IF NOT EXISTS idx_ecm_plant       ON ecm_requests (plant_id);
CREATE INDEX IF NOT EXISTS idx_ecm_department  ON ecm_requests (department_id);
CREATE INDEX IF NOT EXISTS idx_ecm_owner       ON ecm_requests (owner_id);
CREATE INDEX IF NOT EXISTS idx_ecm_requestor   ON ecm_requests (requestor_id);
CREATE INDEX IF NOT EXISTS idx_ecm_priority    ON ecm_requests (priority);
CREATE INDEX IF NOT EXISTS idx_ecm_due         ON ecm_requests (due_date) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_ecm_created     ON ecm_requests (created_at);
CREATE INDEX IF NOT EXISTS idx_ecm_active      ON ecm_requests (is_deleted) WHERE NOT is_deleted;

-- ---- ECR (Engineering Change Request) --------------------------------------
CREATE TABLE IF NOT EXISTS ecr_records (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ecr_number        citext UNIQUE,                               -- generated by trigger (0009)
  ecm_request_id    uuid NOT NULL REFERENCES ecm_requests(id) ON DELETE CASCADE,
  title             text NOT NULL,
  solution_description text,
  impact_analysis   text,
  current_state_id  uuid REFERENCES wf_states(id) ON DELETE SET NULL,
  status_category   citext REFERENCES wf_state_categories(code),
  state_entered_at  timestamptz NOT NULL DEFAULT now(),
  crb_meeting_date  date,
  priority          priority_level NOT NULL DEFAULT 'medium',
  risk_level        risk_level     NOT NULL DEFAULT 'low',
  owner_id          uuid REFERENCES profiles(id) ON DELETE SET NULL,
  d365_ecr_id       text UNIQUE,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  created_by        uuid REFERENCES profiles(id) ON DELETE SET NULL
);
COMMENT ON TABLE ecr_records IS 'Engineering Change Request spawned from an accepted pre-request.';
CREATE INDEX IF NOT EXISTS idx_ecr_ecm   ON ecr_records (ecm_request_id);
CREATE INDEX IF NOT EXISTS idx_ecr_state ON ecr_records (current_state_id);

-- ---- ECO (Engineering Change Order) ----------------------------------------
CREATE TABLE IF NOT EXISTS eco_records (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  eco_number          citext UNIQUE,                             -- generated by trigger (0009)
  ecm_request_id      uuid NOT NULL REFERENCES ecm_requests(id) ON DELETE CASCADE,
  ecr_record_id       uuid REFERENCES ecr_records(id) ON DELETE SET NULL,
  title               text NOT NULL,
  implementation_plan text,
  current_state_id    uuid REFERENCES wf_states(id) ON DELETE SET NULL,
  status_category     citext REFERENCES wf_state_categories(code),
  state_entered_at    timestamptz NOT NULL DEFAULT now(),
  planned_release_date date,
  actual_release_date  date,
  ppap_status         text CHECK (ppap_status IN ('not_required','pending','submitted','approved','rejected')),
  owner_id            uuid REFERENCES profiles(id) ON DELETE SET NULL,
  d365_eco_id         text UNIQUE,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  created_by          uuid REFERENCES profiles(id) ON DELETE SET NULL
);
COMMENT ON TABLE eco_records IS 'Engineering Change Order spawned from an accepted ECR; drives implementation.';
CREATE INDEX IF NOT EXISTS idx_eco_ecm   ON eco_records (ecm_request_id);
CREATE INDEX IF NOT EXISTS idx_eco_ecr   ON eco_records (ecr_record_id);
CREATE INDEX IF NOT EXISTS idx_eco_state ON eco_records (current_state_id);

-- ---- Generic entity links (Related ECM / ECR / ECO / items) ----------------
CREATE TABLE IF NOT EXISTS ecm_links (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_type   entity_type NOT NULL,
  source_id     uuid NOT NULL,
  target_type   entity_type NOT NULL,
  target_id     uuid NOT NULL,
  relation_type text NOT NULL DEFAULT 'related'
                  CHECK (relation_type IN ('related','duplicate','supersedes','superseded_by','blocks','blocked_by','caused_by','derived_from')),
  note          text,
  created_by    uuid REFERENCES profiles(id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_type, source_id, target_type, target_id, relation_type),
  CHECK (NOT (source_type = target_type AND source_id = target_id))
);
CREATE INDEX IF NOT EXISTS idx_ecm_links_source ON ecm_links (source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_ecm_links_target ON ecm_links (target_type, target_id);

-- ---- Affected items / BOM ---------------------------------------------------
CREATE TABLE IF NOT EXISTS ecm_affected_items (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ecm_request_id uuid NOT NULL REFERENCES ecm_requests(id) ON DELETE CASCADE,
  item_id        uuid NOT NULL REFERENCES items(id) ON DELETE RESTRICT,
  bom_id         uuid REFERENCES boms(id) ON DELETE SET NULL,
  change_kind    text NOT NULL DEFAULT 'modify'
                   CHECK (change_kind IN ('add','modify','remove','replace')),
  from_revision  text,
  to_revision    text,
  note           text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ecm_request_id, item_id)
);
CREATE INDEX IF NOT EXISTS idx_affected_items_item ON ecm_affected_items (item_id);

-- ---- State transition history (append-only; powers timeline + analytics) ---
CREATE TABLE IF NOT EXISTS ecm_state_history (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity_type    entity_type NOT NULL,
  entity_id      uuid NOT NULL,
  ecm_request_id uuid REFERENCES ecm_requests(id) ON DELETE CASCADE,  -- denormalized for fast joins
  workflow_id    uuid REFERENCES wf_workflows(id) ON DELETE SET NULL,
  from_state_id  uuid REFERENCES wf_states(id) ON DELETE SET NULL,
  to_state_id    uuid REFERENCES wf_states(id) ON DELETE SET NULL,
  transition_id  uuid REFERENCES wf_transitions(id) ON DELETE SET NULL,
  action_code    citext,
  performed_by   uuid REFERENCES profiles(id) ON DELETE SET NULL,
  performed_at   timestamptz NOT NULL DEFAULT now(),
  comment        text,
  dwell_seconds  bigint                                            -- time spent in from_state
);
CREATE INDEX IF NOT EXISTS idx_state_history_entity ON ecm_state_history (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_state_history_ecm    ON ecm_state_history (ecm_request_id);
CREATE INDEX IF NOT EXISTS idx_state_history_to     ON ecm_state_history (to_state_id);
CREATE INDEX IF NOT EXISTS idx_state_history_when   ON ecm_state_history (performed_at);

-- ---- updated_at triggers ----------------------------------------------------
CREATE TRIGGER trg_ecm_updated BEFORE UPDATE ON ecm_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_ecr_updated BEFORE UPDATE ON ecr_records  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_eco_updated BEFORE UPDATE ON eco_records  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
